import type { Metadata } from 'next';
import './globals.css';
import { Lato } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Natours | Exciting tours for adventurous people',
  description: 'Generated by create next app',
};

const lato = Lato({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
  style: ['italic', 'normal'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased ${lato.className}`}>{children}</body>
    </html>
  );
}
